name: Build and Upload Binary
on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
      ext:
        required: true
        type: string
      os_name:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  build:
    name: 🧱 Build 🧱
    runs-on: ${{ inputs.os }}

    steps:
      # -----------------------------------------------------------
      # Info
      # -----------------------------------------------------------
      - name: 📋 Info 📋
        run: |
          echo "Running for ${{ inputs.os_name }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Client secrets
        run: |
          echo '${{ secrets.GOOGLE_CLIENT_SECRET }}' > client_secret.json

      - name: Build binary with PyInstaller
        run: |
          pyinstaller cenv.spec
          mv dist/cenv${{inputs.ext}} dist/${{ inputs.file }}

      - name: Upload Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.file }}
          path: dist/${{ inputs.file }}

      - name: Clean Up for UNIX systems
        if: ${{ inputs.os_name != 'windows' }}
        run: rm -rf build, dist

      - name: Clean Up for Windows system
        if: ${{ inputs.os_name == 'windows' }}
        run: Remove-Item -Recurse -Force build, dist
