name: Build and Upload Binary
on:
  workflow_call:
    inputs:
      ext:
        required: true
        type: string
      os-short:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  build:
    name: 🧱 Build 🧱
    runs-on: ${{inputs.os}}

    steps:
      # -----------------------------------------------------------
      # Info
      # -----------------------------------------------------------
      - name: 📋 Info 📋
        run: |
          echo "Running for ${{inputs.os-short}}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build binary with PyInstaller
        run: |
          pyinstaller cenv.spec

      - name: Upload Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cenv-${{inputs.os-short}}
          path: dist/cenv${{inputs.ext}}

      - name: Clean Up for UNIX systems
        if: ${{ inputs.os-short != 'windows' }}
        run: rm -rf build, dist

      - name: Clean Up for Windows system
        if: ${{ inputs.os-short == 'windows' }}
        run: Remove-Item -Recurse -Force build, dist
